spring.application.name=SecureEventHub

spring.datasource.url = jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username =${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.data.redis.host=localhost
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.database=1


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

prox.app.jwtSecret=${JWT_SECRET}
prox.app.jwtExpirationMs=${JWT_EXP}
prox.app.jwtRefreshExpirationMs=${JWT_REFRESH_EXP}


